#!/bin/sh
# /etc/init.d/startup_script

start() {
    echo "Starting video playback script"
    python3 /usr/bin/bcvp/script.py
}

stop() {
    echo "Stopping video playback script"
    # Any commands to gracefully stop your script
}

case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  *)
    echo "Usage: $0 {start|stop|restart}"
    exit 1
esac

exit 0